# Created by and for Qt Creator. This file was created for editing the project sources only.
# You may attempt to use it for building too, by modifying this file here.

TARGET = HelloDpiWorker

QT  += widgets core gui webenginewidgets

HEADERS = \
   $$PWD/boost/config/abi/borland_prefix.hpp \
   $$PWD/boost/config/abi/borland_suffix.hpp \
   $$PWD/boost/config/abi/msvc_prefix.hpp \
   $$PWD/boost/config/abi/msvc_suffix.hpp \
   $$PWD/boost/config/compiler/borland.hpp \
   $$PWD/boost/config/compiler/clang.hpp \
   $$PWD/boost/config/compiler/codegear.hpp \
   $$PWD/boost/config/compiler/comeau.hpp \
   $$PWD/boost/config/compiler/common_edg.hpp \
   $$PWD/boost/config/compiler/compaq_cxx.hpp \
   $$PWD/boost/config/compiler/cray.hpp \
   $$PWD/boost/config/compiler/digitalmars.hpp \
   $$PWD/boost/config/compiler/gcc.hpp \
   $$PWD/boost/config/compiler/gcc_xml.hpp \
   $$PWD/boost/config/compiler/greenhills.hpp \
   $$PWD/boost/config/compiler/hp_acc.hpp \
   $$PWD/boost/config/compiler/intel.hpp \
   $$PWD/boost/config/compiler/kai.hpp \
   $$PWD/boost/config/compiler/metrowerks.hpp \
   $$PWD/boost/config/compiler/mpw.hpp \
   $$PWD/boost/config/compiler/nvcc.hpp \
   $$PWD/boost/config/compiler/pathscale.hpp \
   $$PWD/boost/config/compiler/pgi.hpp \
   $$PWD/boost/config/compiler/sgi_mipspro.hpp \
   $$PWD/boost/config/compiler/sunpro_cc.hpp \
   $$PWD/boost/config/compiler/vacpp.hpp \
   $$PWD/boost/config/compiler/visualc.hpp \
   $$PWD/boost/config/no_tr1/cmath.hpp \
   $$PWD/boost/config/no_tr1/complex.hpp \
   $$PWD/boost/config/no_tr1/functional.hpp \
   $$PWD/boost/config/no_tr1/memory.hpp \
   $$PWD/boost/config/no_tr1/utility.hpp \
   $$PWD/boost/config/platform/aix.hpp \
   $$PWD/boost/config/platform/amigaos.hpp \
   $$PWD/boost/config/platform/beos.hpp \
   $$PWD/boost/config/platform/bsd.hpp \
   $$PWD/boost/config/platform/cray.hpp \
   $$PWD/boost/config/platform/cygwin.hpp \
   $$PWD/boost/config/platform/hpux.hpp \
   $$PWD/boost/config/platform/irix.hpp \
   $$PWD/boost/config/platform/linux.hpp \
   $$PWD/boost/config/platform/macos.hpp \
   $$PWD/boost/config/platform/qnxnto.hpp \
   $$PWD/boost/config/platform/solaris.hpp \
   $$PWD/boost/config/platform/symbian.hpp \
   $$PWD/boost/config/platform/vms.hpp \
   $$PWD/boost/config/platform/vxworks.hpp \
   $$PWD/boost/config/platform/win32.hpp \
   $$PWD/boost/config/stdlib/dinkumware.hpp \
   $$PWD/boost/config/stdlib/libcomo.hpp \
   $$PWD/boost/config/stdlib/libcpp.hpp \
   $$PWD/boost/config/stdlib/libstdcpp3.hpp \
   $$PWD/boost/config/stdlib/modena.hpp \
   $$PWD/boost/config/stdlib/msl.hpp \
   $$PWD/boost/config/stdlib/roguewave.hpp \
   $$PWD/boost/config/stdlib/sgi.hpp \
   $$PWD/boost/config/stdlib/stlport.hpp \
   $$PWD/boost/config/stdlib/vacpp.hpp \
   $$PWD/boost/config/abi_prefix.hpp \
   $$PWD/boost/config/abi_suffix.hpp \
   $$PWD/boost/config/auto_link.hpp \
   $$PWD/boost/config/posix_features.hpp \
   $$PWD/boost/config/requires_threads.hpp \
   $$PWD/boost/config/select_compiler_config.hpp \
   $$PWD/boost/config/select_platform_config.hpp \
   $$PWD/boost/config/select_stdlib_config.hpp \
   $$PWD/boost/config/suffix.hpp \
   $$PWD/boost/config/user.hpp \
   $$PWD/boost/config/warning_disable.hpp \
   $$PWD/boost/detail/workaround.hpp \
   $$PWD/boost/exception/detail/attribute_noreturn.hpp \
   $$PWD/boost/exception/exception.hpp \
   $$PWD/boost/locale/definitions.hpp \
   $$PWD/boost/locale/encoding_errors.hpp \
   $$PWD/boost/locale/encoding_utf.hpp \
   $$PWD/boost/locale/utf.hpp \
   $$PWD/boost/mpl/aux_/config/adl.hpp \
   $$PWD/boost/mpl/aux_/config/arrays.hpp \
   $$PWD/boost/mpl/aux_/config/ctps.hpp \
   $$PWD/boost/mpl/aux_/config/dtp.hpp \
   $$PWD/boost/mpl/aux_/config/eti.hpp \
   $$PWD/boost/mpl/aux_/config/gcc.hpp \
   $$PWD/boost/mpl/aux_/config/integral.hpp \
   $$PWD/boost/mpl/aux_/config/intel.hpp \
   $$PWD/boost/mpl/aux_/config/lambda.hpp \
   $$PWD/boost/mpl/aux_/config/msvc.hpp \
   $$PWD/boost/mpl/aux_/config/nttp.hpp \
   $$PWD/boost/mpl/aux_/config/overload_resolution.hpp \
   $$PWD/boost/mpl/aux_/config/preprocessor.hpp \
   $$PWD/boost/mpl/aux_/config/static_constant.hpp \
   $$PWD/boost/mpl/aux_/config/ttp.hpp \
   $$PWD/boost/mpl/aux_/config/workaround.hpp \
   $$PWD/boost/mpl/aux_/preprocessor/def_params_tail.hpp \
   $$PWD/boost/mpl/aux_/preprocessor/enum.hpp \
   $$PWD/boost/mpl/aux_/preprocessor/filter_params.hpp \
   $$PWD/boost/mpl/aux_/preprocessor/params.hpp \
   $$PWD/boost/mpl/aux_/preprocessor/sub.hpp \
   $$PWD/boost/mpl/aux_/preprocessor/tuple.hpp \
   $$PWD/boost/mpl/aux_/adl_barrier.hpp \
   $$PWD/boost/mpl/aux_/arity.hpp \
   $$PWD/boost/mpl/aux_/integral_wrapper.hpp \
   $$PWD/boost/mpl/aux_/lambda_arity_param.hpp \
   $$PWD/boost/mpl/aux_/lambda_support.hpp \
   $$PWD/boost/mpl/aux_/na.hpp \
   $$PWD/boost/mpl/aux_/na_fwd.hpp \
   $$PWD/boost/mpl/aux_/na_spec.hpp \
   $$PWD/boost/mpl/aux_/nttp_decl.hpp \
   $$PWD/boost/mpl/aux_/static_cast.hpp \
   $$PWD/boost/mpl/aux_/template_arity_fwd.hpp \
   $$PWD/boost/mpl/aux_/value_wknd.hpp \
   $$PWD/boost/mpl/aux_/yes_no.hpp \
   $$PWD/boost/mpl/limits/arity.hpp \
   $$PWD/boost/mpl/bool.hpp \
   $$PWD/boost/mpl/bool_fwd.hpp \
   $$PWD/boost/mpl/eval_if.hpp \
   $$PWD/boost/mpl/identity.hpp \
   $$PWD/boost/mpl/if.hpp \
   $$PWD/boost/mpl/int.hpp \
   $$PWD/boost/mpl/int_fwd.hpp \
   $$PWD/boost/mpl/integral_c.hpp \
   $$PWD/boost/mpl/integral_c_fwd.hpp \
   $$PWD/boost/mpl/integral_c_tag.hpp \
   $$PWD/boost/mpl/lambda_fwd.hpp \
   $$PWD/boost/mpl/void_fwd.hpp \
   $$PWD/boost/preprocessor/arithmetic/add.hpp \
   $$PWD/boost/preprocessor/arithmetic/dec.hpp \
   $$PWD/boost/preprocessor/arithmetic/inc.hpp \
   $$PWD/boost/preprocessor/arithmetic/sub.hpp \
   $$PWD/boost/preprocessor/array/data.hpp \
   $$PWD/boost/preprocessor/array/elem.hpp \
   $$PWD/boost/preprocessor/array/size.hpp \
   $$PWD/boost/preprocessor/config/config.hpp \
   $$PWD/boost/preprocessor/control/detail/dmc/while.hpp \
   $$PWD/boost/preprocessor/control/detail/edg/while.hpp \
   $$PWD/boost/preprocessor/control/detail/msvc/while.hpp \
   $$PWD/boost/preprocessor/control/detail/while.hpp \
   $$PWD/boost/preprocessor/control/expr_iif.hpp \
   $$PWD/boost/preprocessor/control/if.hpp \
   $$PWD/boost/preprocessor/control/iif.hpp \
   $$PWD/boost/preprocessor/control/while.hpp \
   $$PWD/boost/preprocessor/debug/error.hpp \
   $$PWD/boost/preprocessor/detail/dmc/auto_rec.hpp \
   $$PWD/boost/preprocessor/detail/auto_rec.hpp \
   $$PWD/boost/preprocessor/detail/check.hpp \
   $$PWD/boost/preprocessor/detail/is_binary.hpp \
   $$PWD/boost/preprocessor/facilities/empty.hpp \
   $$PWD/boost/preprocessor/facilities/identity.hpp \
   $$PWD/boost/preprocessor/facilities/overload.hpp \
   $$PWD/boost/preprocessor/iteration/detail/bounds/lower1.hpp \
   $$PWD/boost/preprocessor/iteration/detail/bounds/lower2.hpp \
   $$PWD/boost/preprocessor/iteration/detail/bounds/lower3.hpp \
   $$PWD/boost/preprocessor/iteration/detail/bounds/lower4.hpp \
   $$PWD/boost/preprocessor/iteration/detail/bounds/lower5.hpp \
   $$PWD/boost/preprocessor/iteration/detail/bounds/upper1.hpp \
   $$PWD/boost/preprocessor/iteration/detail/bounds/upper2.hpp \
   $$PWD/boost/preprocessor/iteration/detail/bounds/upper3.hpp \
   $$PWD/boost/preprocessor/iteration/detail/bounds/upper4.hpp \
   $$PWD/boost/preprocessor/iteration/detail/bounds/upper5.hpp \
   $$PWD/boost/preprocessor/iteration/detail/iter/forward1.hpp \
   $$PWD/boost/preprocessor/iteration/detail/iter/forward2.hpp \
   $$PWD/boost/preprocessor/iteration/detail/iter/forward3.hpp \
   $$PWD/boost/preprocessor/iteration/detail/iter/forward4.hpp \
   $$PWD/boost/preprocessor/iteration/detail/iter/forward5.hpp \
   $$PWD/boost/preprocessor/iteration/detail/iter/reverse1.hpp \
   $$PWD/boost/preprocessor/iteration/detail/iter/reverse2.hpp \
   $$PWD/boost/preprocessor/iteration/detail/iter/reverse3.hpp \
   $$PWD/boost/preprocessor/iteration/detail/iter/reverse4.hpp \
   $$PWD/boost/preprocessor/iteration/detail/iter/reverse5.hpp \
   $$PWD/boost/preprocessor/iteration/detail/finish.hpp \
   $$PWD/boost/preprocessor/iteration/detail/local.hpp \
   $$PWD/boost/preprocessor/iteration/detail/rlocal.hpp \
   $$PWD/boost/preprocessor/iteration/detail/self.hpp \
   $$PWD/boost/preprocessor/iteration/detail/start.hpp \
   $$PWD/boost/preprocessor/iteration/iterate.hpp \
   $$PWD/boost/preprocessor/iteration/local.hpp \
   $$PWD/boost/preprocessor/iteration/self.hpp \
   $$PWD/boost/preprocessor/list/detail/dmc/fold_left.hpp \
   $$PWD/boost/preprocessor/list/detail/edg/fold_left.hpp \
   $$PWD/boost/preprocessor/list/detail/edg/fold_right.hpp \
   $$PWD/boost/preprocessor/list/detail/fold_left.hpp \
   $$PWD/boost/preprocessor/list/detail/fold_right.hpp \
   $$PWD/boost/preprocessor/list/adt.hpp \
   $$PWD/boost/preprocessor/list/fold_left.hpp \
   $$PWD/boost/preprocessor/list/fold_right.hpp \
   $$PWD/boost/preprocessor/list/for_each_i.hpp \
   $$PWD/boost/preprocessor/list/reverse.hpp \
   $$PWD/boost/preprocessor/logical/and.hpp \
   $$PWD/boost/preprocessor/logical/bitand.hpp \
   $$PWD/boost/preprocessor/logical/bool.hpp \
   $$PWD/boost/preprocessor/logical/compl.hpp \
   $$PWD/boost/preprocessor/punctuation/comma.hpp \
   $$PWD/boost/preprocessor/punctuation/comma_if.hpp \
   $$PWD/boost/preprocessor/repetition/detail/dmc/for.hpp \
   $$PWD/boost/preprocessor/repetition/detail/edg/for.hpp \
   $$PWD/boost/preprocessor/repetition/detail/msvc/for.hpp \
   $$PWD/boost/preprocessor/repetition/detail/for.hpp \
   $$PWD/boost/preprocessor/repetition/enum_params.hpp \
   $$PWD/boost/preprocessor/repetition/for.hpp \
   $$PWD/boost/preprocessor/repetition/repeat.hpp \
   $$PWD/boost/preprocessor/slot/detail/counter.hpp \
   $$PWD/boost/preprocessor/slot/detail/def.hpp \
   $$PWD/boost/preprocessor/slot/detail/shared.hpp \
   $$PWD/boost/preprocessor/slot/detail/slot1.hpp \
   $$PWD/boost/preprocessor/slot/detail/slot2.hpp \
   $$PWD/boost/preprocessor/slot/detail/slot3.hpp \
   $$PWD/boost/preprocessor/slot/detail/slot4.hpp \
   $$PWD/boost/preprocessor/slot/detail/slot5.hpp \
   $$PWD/boost/preprocessor/slot/slot.hpp \
   $$PWD/boost/preprocessor/tuple/eat.hpp \
   $$PWD/boost/preprocessor/tuple/elem.hpp \
   $$PWD/boost/preprocessor/tuple/rem.hpp \
   $$PWD/boost/preprocessor/tuple/to_list.hpp \
   $$PWD/boost/preprocessor/variadic/elem.hpp \
   $$PWD/boost/preprocessor/variadic/size.hpp \
   $$PWD/boost/preprocessor/cat.hpp \
   $$PWD/boost/preprocessor/comma_if.hpp \
   $$PWD/boost/preprocessor/empty.hpp \
   $$PWD/boost/preprocessor/enum_params.hpp \
   $$PWD/boost/preprocessor/identity.hpp \
   $$PWD/boost/preprocessor/inc.hpp \
   $$PWD/boost/preprocessor/iterate.hpp \
   $$PWD/boost/preprocessor/repeat.hpp \
   $$PWD/boost/type_traits/detail/bool_trait_def.hpp \
   $$PWD/boost/type_traits/detail/bool_trait_undef.hpp \
   $$PWD/boost/type_traits/detail/cv_traits_impl.hpp \
   $$PWD/boost/type_traits/detail/false_result.hpp \
   $$PWD/boost/type_traits/detail/ice_and.hpp \
   $$PWD/boost/type_traits/detail/ice_eq.hpp \
   $$PWD/boost/type_traits/detail/ice_not.hpp \
   $$PWD/boost/type_traits/detail/ice_or.hpp \
   $$PWD/boost/type_traits/detail/is_function_ptr_helper.hpp \
   $$PWD/boost/type_traits/detail/is_function_ptr_tester.hpp \
   $$PWD/boost/type_traits/detail/template_arity_spec.hpp \
   $$PWD/boost/type_traits/detail/type_trait_def.hpp \
   $$PWD/boost/type_traits/detail/type_trait_undef.hpp \
   $$PWD/boost/type_traits/detail/wrap.hpp \
   $$PWD/boost/type_traits/detail/yes_no_type.hpp \
   $$PWD/boost/type_traits/msvc/remove_bounds.hpp \
   $$PWD/boost/type_traits/msvc/remove_reference.hpp \
   $$PWD/boost/type_traits/msvc/typeof.hpp \
   $$PWD/boost/type_traits/add_pointer.hpp \
   $$PWD/boost/type_traits/add_reference.hpp \
   $$PWD/boost/type_traits/broken_compiler_spec.hpp \
   $$PWD/boost/type_traits/config.hpp \
   $$PWD/boost/type_traits/decay.hpp \
   $$PWD/boost/type_traits/ice.hpp \
   $$PWD/boost/type_traits/integral_constant.hpp \
   $$PWD/boost/type_traits/is_array.hpp \
   $$PWD/boost/type_traits/is_const.hpp \
   $$PWD/boost/type_traits/is_function.hpp \
   $$PWD/boost/type_traits/is_lvalue_reference.hpp \
   $$PWD/boost/type_traits/is_reference.hpp \
   $$PWD/boost/type_traits/is_rvalue_reference.hpp \
   $$PWD/boost/type_traits/is_same.hpp \
   $$PWD/boost/type_traits/remove_bounds.hpp \
   $$PWD/boost/type_traits/remove_reference.hpp \
   $$PWD/boost/utility/enable_if.hpp \
   $$PWD/boost/any.hpp \
   $$PWD/boost/config.hpp \
   $$PWD/boost/cstdint.hpp \
   $$PWD/boost/current_function.hpp \
   $$PWD/boost/limits.hpp \
   $$PWD/boost/static_assert.hpp \
   $$PWD/boost/throw_exception.hpp \
   $$PWD/boost/version.hpp \
    plistcpp/base64.hpp \
    plistcpp/Plist.hpp \
    plistcpp/PlistDate.hpp \
    plistcpp/pugiconfig.hpp \
    plistcpp/pugixml.hpp \
    configfiledao.h \
    constans.h \
    displaysao.h \
    displaytab.h \
    globalvariables.h \
    tabcontainer.h

SOURCES = \
   $$PWD/main.cpp \
    plistcpp/Plist.cpp \
    plistcpp/PlistDate.cpp \
    plistcpp/pugixml.cpp \
    utils.cpp \
    configfiledao.cpp \
    displaysao.cpp \
    displaytab.cpp \
    tabcontainer.cpp

INCLUDEPATH =

#DEFINES =

FORMS += \
    displaytab.ui \
    tabcontainer.ui

SampleConfigFile.files = DisplayProductID-a02e
SampleConfigFile.path = Contents/Resources

QMAKE_BUNDLE_DATA += SampleConfigFile

RESOURCES += \
    res.qrc

